const typeActions = {
  FETCH_SWEETS_STARTED: 'FETCH_SWEETS_STARTED',
  FETCH_SWEETS_FULFILLED: 'FETCH_SWEETS_FULFILLED',
  FETCH_SWEETS_REJECTED: 'FETCH_SWEETS_REJECTED',

  // CLEAR_SWEETS: 'CLEAR_SWEETS',
  // CLEAR_SWEET: 'CLEAR_SWEET',
  // CREATE_SWEET: 'CREATE_SWEET',
  // DELETE_SWEET: 'DELETE_SWEET',
  // LIKE_SWEET: 'LIKE_SWEET',
  // UPDATE_SWEET: 'UPDATE_SWEET',
  // CREATE_SWEET_COMMENT: 'CREATE_SWEET_COMMENT',
  // DELETE_SWEET_COMMENT: 'DELETE_SWEET_COMMENT',
};

export default typeActions;
